// Generates the 3D tile kit for the voxel structures: one OBJ per piece in voxels/tiles/, plus tileset.json.
// Run: node tools/make-tiles.js
//
// Conventions (also written into tileset.json):
//  - 1 unit = 1 voxel. A cell is 4 units across and 4 tall.
//  - +Y is up. Every piece is authored in its cell's local frame: x and z from -2 to +2, floor at y = 0.
//  - Side pieces (walls, windows, doors, rails…) are authored on the +Z face. The placer rotates them about Y:
//    +Z 0°, +X 90°, -Z 180°, -X 270° (counter-clockwise seen from above).
//  - Wall pieces are half a voxel thick (z 1.5–2); the neighbouring cell supplies the other half.
//  - For Unreal later: import with Z-up conversion (the axes swap on import) and a scale factor for the voxel size.
const fs = require('fs'), path = require('path');
const OUT = path.join(__dirname, '..', 'voxels', 'tiles');
fs.mkdirSync(OUT, { recursive: true });

// ---- tiny mesh builder: axis-aligned boxes, emitted as quads with normals ----
function Mesh() { this.boxes = []; }
Mesh.prototype.box = function (x0, y0, z0, x1, y1, z1) {
  if (x1 - x0 <= 1e-6 || y1 - y0 <= 1e-6 || z1 - z0 <= 1e-6) return this;
  this.boxes.push([Math.min(x0, x1), Math.min(y0, y1), Math.min(z0, z1), Math.max(x0, x1), Math.max(y0, y1), Math.max(z0, z1)]);
  return this;
};
Mesh.prototype.obj = function (name) {
  const v = [], f = [], r = n => +n.toFixed(4);
  const N = ['0 0 -1', '0 0 1', '-1 0 0', '1 0 0', '0 -1 0', '0 1 0'];
  for (const [a, b, c, d, e, g] of this.boxes) {
    const base = v.length;
    // 8 corners: index = x | y<<1 | z<<2
    for (let i = 0; i < 8; i++) v.push(`v ${r(i & 1 ? d : a)} ${r(i & 2 ? e : b)} ${r(i & 4 ? g : c)}`);
    const q = (n, i0, i1, i2, i3) => f.push(`f ${base + i0 + 1}//${n} ${base + i1 + 1}//${n} ${base + i2 + 1}//${n} ${base + i3 + 1}//${n}`);
    q(1, 0, 2, 3, 1); q(2, 4, 5, 7, 6); q(3, 0, 4, 6, 2); q(4, 1, 3, 7, 5); q(5, 0, 1, 5, 4); q(6, 2, 6, 7, 3);
  }
  return `# ${name} — generated by tools/make-tiles.js\n# 1 unit = 1 voxel, +Y up, cell frame x,z in [-2,2]\no ${name}\n${N.map(n => 'vn ' + n).join('\n')}\n${v.join('\n')}\n${f.join('\n')}\n`;
};
const M = () => new Mesh();

// ---- pieces ----
const pieces = {};
const add = (name, family, mesh, extra) => { pieces[name] = Object.assign({ file: name + '.obj', family }, extra || {}); fs.writeFileSync(path.join(OUT, name + '.obj'), mesh.obj(name)); };
const Z0 = 1.5, Z1 = 2; // wall slab on the +Z face

// walls (WFC chooses between these)
const wall = () => M().box(-2, 1, Z0, 2, 4, Z1);
add('wall_plain', 'wall', wall(), { weight: 4 });
{ const m = wall(); for (const x of [-1.25, 0, 1.25]) m.box(x - 0.15, 1, Z0 - 0.25, x + 0.15, 4, Z0); add('wall_ribbed', 'wall', m, { weight: 2 }); } // vertical pilasters
{ const m = wall().box(-2, 2.2, Z0 - 0.2, 2, 2.8, Z0); add('wall_banded', 'wall', m, { weight: 2 }); } // a horizontal band

// windows: a slot under the ceiling, as in the voxels (y 3–4 across the interior)
const windowFrame = () => M().box(-2, 1, Z0, 2, 3, Z1).box(-2, 3, Z0, -1.5, 4, Z1).box(1.5, 3, Z0, 2, 4, Z1);
add('window_slot', 'window', windowFrame(), { weight: 3 });
{ const m = windowFrame(); for (const x of [-0.75, 0, 0.75]) m.box(x - 0.07, 3, Z0 + 0.15, x + 0.07, 4, Z1 - 0.15); add('window_barred', 'window', m, { weight: 2 }); }

// doors: one voxel wide, two tall, at offset -1, 0 or +1 along the face (the generator moves doors off a stair row)
for (const [nm, o] of [['door_c', 0], ['door_n', -1], ['door_p', 1]]) {
  const m = M().box(-2, 1, Z0, o - 0.5, 4, Z1).box(o + 0.5, 1, Z0, 2, 4, Z1).box(o - 0.5, 3, Z0, o + 0.5, 4, Z1);
  m.box(o - 0.65, 1, Z0 - 0.1, o - 0.5, 3.15, Z1 + 0.1).box(o + 0.5, 1, Z0 - 0.1, o + 0.65, 3.15, Z1 + 0.1).box(o - 0.65, 3, Z0 - 0.1, o + 0.65, 3.15, Z1 + 0.1); // frame
  add(nm, 'door', m, { offset: o });
}
// arch: the full 3-voxel interior, two tall, with a lintel
add('arch', 'arch', M().box(-2, 1, Z0, -1.5, 4, Z1).box(1.5, 1, Z0, 2, 4, Z1).box(-1.5, 3, Z0, 1.5, 4, Z1));
// entrance: an arch with a heavy frame on the outside
add('entrance', 'entrance', M().box(-2, 1, Z0, -1.5, 4, Z1).box(1.5, 1, Z0, 2, 4, Z1).box(-1.5, 3, Z0, 1.5, 4, Z1)
  .box(-2.2, 1, Z1, -1.5, 4.3, Z1 + 0.4).box(1.5, 1, Z1, 2.2, 4.3, Z1 + 0.4).box(-2.2, 3.6, Z1, 2.2, 4.3, Z1 + 0.4));
// rail for walkway decks: posts and a top bar, two voxels tall over the full voxel line
{ const m = M(); for (const x of [-2, -1, 0, 1, 2]) m.box(x - 0.2, 1, 1.6, x + 0.2, 3, 2.4); m.box(-2.4, 2.6, 1.6, 2.4, 3, 2.4).box(-2.4, 1.6, 1.85, 2.4, 1.8, 2.15); add('rail', 'rail', m); }

// floors, roofs, decks
add('floor_plain', 'floor', M().box(-2, 0, -2, 2, 1, 2), { weight: 4 });
{ const m = M().box(-2, 0, -2, 2, 0.4, 2).box(-2, 0.4, -2, 2, 1, -1.6).box(-2, 0.4, 1.6, 2, 1, 2).box(-2, 0.4, -1.6, -1.6, 1, 1.6).box(1.6, 0.4, -1.6, 2, 1, 1.6);
  for (const x of [-1, 0, 1]) m.box(x - 0.12, 0.4, -1.6, x + 0.12, 1, 1.6); add('floor_grate', 'floor', m, { weight: 1 }); }
// floor with a hole above an in-cell stair: the hole covers x 0..1 (voxels 2–3) on stair row 1 or 3
for (const row of [1, 3]) {
  const z0 = row - 2.5, z1 = row - 1.5;
  add('floor_hole_r' + row, 'floor_hole', M().box(-2, 0, -2, 2, 1, z0).box(-2, 0, z1, 2, 1, 2).box(-2, 0, z0, -0.5, 1, z1).box(1.5, 0, z0, 2, 1, z1), { row });
  // the flight itself: three steps along +x in that row
  const st = M(); for (let s = 0; s < 3; s++) st.box(s - 1.5, 1, z0, s - 0.5, 2 + s, z1);
  add('stair_r' + row, 'stair', st, { row });
}
add('roof_plain', 'roof', M().box(-2, 4, -2, 2, 5, 2), { weight: 3 });
{ const m = M().box(-2, 4, -2, 2, 5, 2).box(-1.2, 5, -1.2, -0.4, 5.6, -0.4).box(0.4, 5, 0.4, 1.2, 5.4, 1.2); add('roof_vents', 'roof', m, { weight: 1 }); }
add('deck_plain', 'deck', M().box(-2, 0, -2, 2, 1, 2), { weight: 3 });
{ const m = M().box(-2, 0.6, -2, 2, 1, -1.5).box(-2, 0.6, 1.5, 2, 1, 2); for (const x of [-1.5, -0.5, 0.5, 1.5]) m.box(x - 0.3, 0.6, -1.5, x + 0.3, 1, 1.5); m.box(-2, 0, -0.3, 2, 0.6, 0.3); add('deck_slats', 'deck', m, { weight: 1 }); }

// stair run: a walkway cell climbing one storey towards +Z (four risers, solid ramp, rail walls 3 above each step)
{ const m = M();
  for (let t = 0; t <= 4; t++) {
    const za = t === 0 ? -2 : t - 2.5, zb = t === 4 ? 2 : t - 1.5, top = t + 1; // walking surface at y = t + 1
    m.box(-1.5, 0, za, 1.5, top, zb);                // tread and ramp under it
    m.box(-2.5, 0, za, -1.5, top + 3, zb);           // left rail wall
    m.box(1.5, 0, za, 2.5, top + 3, zb);             // right rail wall
  }
  add('stair_run', 'stair_run', m); }

// shaft ladder against the +Z wall, and the solid mass of monoliths
{ const m = M().box(-0.9, 0, 1.2, -0.7, 4, 1.4).box(0.7, 0, 1.2, 0.9, 4, 1.4); for (const y of [0.5, 1.5, 2.5, 3.5]) m.box(-0.7, y - 0.06, 1.25, 0.7, y + 0.06, 1.35); add('shaft_ladder', 'shaft', m); }
add('mass_plain', 'mass', M().box(-2, 0, -2, 2, 4, 2), { weight: 3 });
{ const m = M().box(-1.8, 0, -1.8, 1.8, 4, 1.8); // a recessed core with corner piers and a band
  m.box(-2, 0, -2, -1.6, 4, -1.6).box(1.6, 0, -2, 2, 4, -1.6).box(-2, 0, 1.6, -1.6, 4, 2).box(1.6, 0, 1.6, 2, 4, 2).box(-2, 1.8, -2, 2, 2.2, 2);
  add('mass_ribbed', 'mass', m, { weight: 1 }); }
add('goal_beacon', 'goal', M().box(-0.3, 1, -0.3, 0.3, 3.6, 0.3).box(-0.6, 1, -0.6, 0.6, 1.3, 0.6));

// ---- manifest ----
const families = {};
for (const [nm, p] of Object.entries(pieces)) (families[p.family] = families[p.family] || []).push(nm);
const tileset = {
  version: 1,
  units: { unit: '1 voxel', cell: 4, storey: 4, up: '+Y', authoredFace: '+Z', rotations: { pz: 0, px: 90, nz: 180, nx: 270 }, pivot: 'centre of the cell floor' },
  unreal: 'Import with Z-up conversion and a uniform scale (voxel size in cm). Rotations become yaw about Z.',
  pieces, families,
  // which family dresses each socket the layer below writes (side faces, the floor face, the ceiling face)
  sockets: {
    side: { wall: 'wall', window: 'window', door: 'door', arch: 'arch', entrance: 'entrance', rail: 'rail' },
    down: { floor: 'floor', stair: 'floor_hole', deck: 'deck' },
    up: { roof: 'roof' }
  },
  // Adjacency rules for WFC between neighbouring pieces of the same family.
  // "v": the same face one storey up or down; "h": the next cell along the same facade; "n": neighbouring floor/roof/deck/mass cells.
  rules: {
    wall: {
      v: { wall_ribbed: ['wall_ribbed'], wall_plain: ['wall_plain', 'wall_banded'], wall_banded: ['wall_plain', 'wall_banded'] },   // pilasters run full height
      h: { wall_banded: ['wall_banded'], wall_plain: ['wall_plain', 'wall_ribbed'], wall_ribbed: ['wall_plain', 'wall_ribbed'] }    // bands run the full width
    },
    window: { h: { window_slot: ['window_slot'], window_barred: ['window_barred'] } },                                                 // one kind of window per ribbon
    deck: { n: { deck_plain: ['deck_plain', 'deck_slats'], deck_slats: ['deck_plain', 'deck_slats'] } },
    mass: { v: { mass_ribbed: ['mass_ribbed'], mass_plain: ['mass_plain'] } }                                                         // a monolith keeps one finish all the way up
  }
};
fs.writeFileSync(path.join(OUT, 'tileset.json'), JSON.stringify(tileset, null, 2) + '\n');
console.log(`${Object.keys(pieces).length} pieces written to voxels/tiles/`);
